# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Taishi Yamasaki"
description: > # this means to ignore newlines until "email:"
   DO MORE OF WHAT MAKES YOU FEEL ALIVE

email: taishi.dev@gmail.com
#blog logo
logo: "/assets/images/logo.jpeg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Taishi Yamasaki'
author: 'Taishi Yamasaki'
author_image: "/assets/images/taishi_author.jpg"

paginate:	10

url: "http://taishi.tech" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@taishi_yamasaki'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/taishi_yamasaki
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    account: @taishi_yamasaki

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/taishi-y
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
